---
# tasks file for docker
- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Create Docker CLI plugin directory
  file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: '0755'
  become: true

- name: Download Docker Compose
  uri:
    url: https://api.github.com/repos/docker/compose/releases/latest
    return_content: yes
  register: docker_compose_latest

- name: Set Docker Compose version
  set_fact:
    docker_compose_version: "{{ docker_compose_latest.json.tag_name }}"

- name: Install Docker Compose /usr/local/lib/docker/cli-plugins
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: '0755'
  become: true

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add user to Docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true

- name: Run Docker Compose
  community.docker.docker_compose_v2:
    project_src: /opt/food-delivery
    state: present
  become: true

