---
# vars file for ec2_launch
aws_region: ap-south-1
ec2_instance_type: t2.micro
ec2_ami_id: ami-0b982602dbb32c5bd
ec2_key_name: aayu-test-codonix
ec2_instance_count: 1
ec2_ssh_user: ec2-user
sg_name: aayu-security
security_group_rules:
  - proto: tcp
    ports: [22, 80, 443]
    cidr_ip: 0.0.0.0/0
  - proto: tcp
    ports: [4000, 5173, 5174]
    cidr_ip: 0.0.0.0/0