name: Provision of Ec2 instance and configuration with Ansible

on:
 push:
  branches:
   - main

jobs: 
 provision_ec2:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout repo
     uses: actions/checkout@v2

   - name: Setup Python 3.x
     uses: actions/setup-python@v2
     with:
      python-version: "3.10"
      
   - name: Install  dependenies
     run: |
      python -m pip install --upgrade pip
      pip install ansible boto3 requests
      ansible-galaxy collection install amazon.aws 
      ansible-galaxy collection install community.docker --force
    
   - name : Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ap-south-1


   - name: Create SSH Key file
     run : |
       mkdir -p ~/.ssh
       echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2_key.pem
       chmod 400 ~/.ssh/ec2_key.pem
    
   - name: Debug SSH key
     run : ls -l ~/.ssh/ec2_key.pem

   - name: Create .env file
     run: |
      echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> backend/.env
      echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> backend/.env
      echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> backend/.env

   - name: Run Ansible Playbook for deploying backend
     run : |
      ansible-playbook \
      -i ansible/inventory \
      -e "ec2_ssh_key_path=~/.ssh/ec2_key.pem" \
      ansible/playbooks/provision_and_configuration.yml
     env: 
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY_ID:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EC2_SSH_KEY_PATH: ~/.ssh/ec2_key.pem
      ANSIBLE_HOST_KEY_CHECKING: False



      


    



    




 
